import type { Metadata } from 'next';
import { Montserrat, Roboto } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

const montserrat = Montserrat({
	subsets: ['latin'],
	display: 'swap',
});

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['300', '400', '500', '700'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Home',
	description: 'Generated by create next app',
	icons: { icon: '/logo.svg' },
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={roboto.className}>
				<ToastContainer />
				{children}
			</body>
		</html>
	);
}
